[project]
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>", "Cedric Lemaitre <c.lemaitre58@gmail.com>"]
channels = ["conda-forge"]
description = "Official website of the the FSGT 71 - Activités Cyclistes"
name = "fsgt71velo.github.io"
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
# generate some of the markdown files
generate_club_listing = { cmd = "python scripts/generate_club_listing.py" }
generate_calendar = { cmd = "python scripts/generate_calendar.py" }
generate_report = { cmd = "python scripts/generate_report.py" }
generate_results = { cmd = "python scripts/generate_results.py" }
generate_listing_update_double_licence = { cmd = "python scripts/generate_listing_update_double_licence.py" }
generate_listing_update_external_riders = { cmd = "python scripts/generate_listing_update_external_riders.py" }
generate_licences = { cmd = "python scripts/generate_licences.py" }
generate_double_licences = { cmd = "python scripts/generate_double_licences.py" }
generate_external_riders = { cmd = "python scripts/generate_external_riders.py" }
generate_commission_bureau = { cmd = "python scripts/generate_commission_bureau.py" }

# ease some mechanical tasks
update_external_riders_spreadsheet = { cmd = "python scripts/update_external_riders_spreadsheet.py" }

# send emails
send_email_update_double_licences = { cmd = "node scripts/send_email_update_double_licences.js", depends-on = ["generate_listing_update_double_licence"] }
send_email_update_external_riders = { cmd = "node scripts/send_email_update_external_riders.js", depends-on = ["generate_listing_update_external_riders"] }

# build the static website
clean = { cmd = "rm -rf output" }
build = { cmd = "pelican content -t theme/fsgt --verbose", depends-on = ["clean", "generate_club_listing", "generate_calendar", "generate_report", "generate_results", "generate_licences", "generate_double_licences", "generate_external_riders", "generate_commission_bureau"] }
preview = { cmd = "pelican --listen", depends-on = ["build"]}

# lint the code
lint = { cmd = "pre-commit install && pre-commit run --all-files" }

# run some test for the python code
tests = { cmd = "pytest -vsl . -n auto", cwd = "scripts/tests" }

[dependencies]
pelican = ">=4.10.2,<5"
markdown = ">=3.6,<4"
pandas = ">=2.2.3,<3"
ipykernel = ">=6.29.5,<7"
google-api-python-client = ">=2.156.0,<3"
pytest = ">=8.3.4,<9"
pytest-xdist = ">=3.6.1,<4"
pre-commit = ">=4.0.1,<5"
openpyxl = ">=3.1.5,<4"
