[project]
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>", "Cedric Lemaitre <c.lemaitre58@gmail.com>"]
channels = ["conda-forge"]
description = "Official website of the the FSGT 71 - Activités Cyclistes"
name = "fsgt71velo.github.io"
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
generate_club_listing = { cmd = "python scripts/generate_club_listing.py" }
generate_calendar = { cmd = "python scripts/generate_calendar.py" }
generate_report = { cmd = "python scripts/generate_report.py" }
generate_results = { cmd = "python scripts/generate_results.py" }

# build the static website
clean = { cmd = "rm -rf output" }
build = { cmd = "pelican content -t theme/fsgt --verbose", depends-on = ["clean", "generate_club_listing", "generate_calendar", "generate_report", "generate_results"] }
preview = { cmd = "pelican --listen", depends-on = ["build"]}

[dependencies]
pelican = ">=4.10.2,<5"
markdown = ">=3.6,<4"
pandas = ">=2.2.3,<3"
ipykernel = ">=6.29.5,<7"
google-api-python-client = ">=2.156.0,<3"
