name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      contents: read
    env:
      GHA_SITE_URL: "https://glemaitre.github.io/fsgt71velo.github.io"
    steps:
      - uses: actions/checkout@v4
      - name: Install French locale
        run: |
          sudo apt-get update
          sudo apt-get install -qq language-pack-fr
          sudo locale-gen fr_FR.UTF-8
          sudo dpkg-reconfigure locales
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.4
          frozen: true
      - name: build website
        run: pixi run build
        env:
          # to get the correct SITEURL
          GHA_SITE_URL: ${{ env.GHA_SITE_URL }}
          # to get the correct locale
          LANG: fr_FR.UTF-8
          LC_ALL: fr_FR.UTF-8
          LANGUAGE: fr_FR:fr
          # to deploy the website that check the content of the google drive
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      - name: deploy website on github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
