name: Update external riders listing

on:
  workflow_dispatch:

jobs:
  update-listing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install French locale
        run: |
          sudo apt-get update
          sudo apt-get install -qq language-pack-fr
          sudo locale-gen fr_FR.UTF-8
          sudo dpkg-reconfigure locales
      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.48.0
          frozen: true
      - name: Update external riders spreadsheet
        run: pixi run update_external_riders_spreadsheet
        env:
          # to get the correct locale
          LANG: fr_FR.UTF-8
          LC_ALL: fr_FR.UTF-8
          LANGUAGE: fr_FR:fr
          # to access the google drive
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
