name: Send update double licenses

on:
  schedule:
    - cron: '30 22 * * *'  # Runs at 22:30 UTC (10:30 PM) every day
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.41.1
          frozen: true
      - name: Generate listing and send email
        run: pixi run send_email_update_double_licences
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          RECIPIENTS_EMAIL: ${{ secrets.RECIPIENTS_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
