name: Send Double Licence Email Update

on:
  schedule:
    # Run every Monday at 8:00 AM UTC
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install SendGrid dependency
        run: npm install @sendgrid/mail

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.4.1
        with:
          pixi-version: v0.39.4

      - name: Generate listing
        run: pixi run generate_listing_update_double_licence
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Send email
        run: pixi run send_email_update_double_licences
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          RECIPIENTS_EMAIL: ${{ secrets.RECIPIENTS_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
